import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export enum SettingsIds {
    EmailProvider = 'provider',
    OAuthClientId = 'client_id',
    OAuthClientSecret = 'client_secret',
    OAuthRedirectUri = 'redirect_uri',
    OutlookClientId = 'outlook_client_id',
    OutlookClientSecret = 'outlook_client_secret',
    OutlookRedirectUri = 'outlook_redirect_uri',
    // LLM Configuration
    LLMProvider = 'llm_provider',
    SelfHostedLLMUrl = 'self_hosted_llm_url',
    OpenAIApiKey = 'openai_api_key',
    GeminiApiKey = 'gemini_api_key',
    GroqApiKey = 'groq_api_key',
}

export const settings: Array<ISetting> = [
    {
        id: SettingsIds.EmailProvider,
        type: SettingType.SELECT,
        packageValue: 'gmail',
        required: true,
        public: false,
        i18nLabel: 'Email_Provider_Label',
        i18nDescription: 'Email_Provider_Description',
        section: 'General',
        values: [
            {
                key: 'gmail',
                i18nLabel: 'Gmail_Label',
            },
            {
                key: 'outlook',
                i18nLabel: 'Outlook_Label',
            },
        ],
    },
    {
        id: SettingsIds.OAuthClientId,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'Google_OAuth_Client_ID_Label',
        i18nDescription: 'Google_OAuth_Client_ID_Description',
    },
    {
        id: SettingsIds.OAuthClientSecret,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'Google_OAuth_Client_Secret_Label',
        i18nDescription: 'Google_OAuth_Client_Secret_Description',
    },
    {
        id: SettingsIds.OAuthRedirectUri,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'OAuth_Redirect_URI_Label',
        i18nDescription: 'OAuth_Redirect_URI_Description',
    },
    {
        id: SettingsIds.OutlookClientId,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'Outlook_OAuth_Client_ID_Label',
        i18nDescription: 'Outlook_OAuth_Client_ID_Description',
    },
    {
        id: SettingsIds.OutlookClientSecret,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'Outlook_OAuth_Client_Secret_Label',
        i18nDescription: 'Outlook_OAuth_Client_Secret_Description',
    },
    {
        id: SettingsIds.OutlookRedirectUri,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        section: 'General',
        i18nLabel: 'Outlook_OAuth_Redirect_URI_Label',
        i18nDescription: 'Outlook_OAuth_Redirect_URI_Description',
    },
    // LLM Configuration Section
    {
        id: SettingsIds.LLMProvider,
        type: SettingType.SELECT,
        packageValue: 'self-hosted',
        required: true,
        public: false,
        section: 'LLM Configuration',
        i18nLabel: 'LLM_Provider_Label',
        i18nDescription: 'LLM_Provider_Description',
        values: [
            {
                key: 'groq',
                i18nLabel: 'LLM_Provider_Groq_Label',
            },
            {
                key: 'gemini',
                i18nLabel: 'LLM_Provider_Gemini_Label',
            },
            {
                key: 'openai',
                i18nLabel: 'LLM_Provider_OpenAI_Label',
            },
            {
                key: 'self-hosted',
                i18nLabel: 'LLM_Provider_SelfHosted_Label',
            },
        ],
    },
    {
        id: SettingsIds.GroqApiKey,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: false,
        public: false,
        section: 'LLM Configuration',
        i18nLabel: 'Groq_API_Key_Label',
        i18nDescription: 'Groq_API_Key_Description',
    },
    {
        id: SettingsIds.GeminiApiKey,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: false,
        public: false,
        section: 'LLM Configuration',
        i18nLabel: 'Gemini_API_Key_Label',
        i18nDescription: 'Gemini_API_Key_Description',
    },
    {
        id: SettingsIds.OpenAIApiKey,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: false,
        public: false,
        section: 'LLM Configuration',
        i18nLabel: 'OpenAI_API_Key_Label',
        i18nDescription: 'OpenAI_API_Key_Description',
    },
    {
        id: SettingsIds.SelfHostedLLMUrl,
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: false,
        section: 'LLM Configuration',
        i18nLabel: 'SelfHosted_LLM_URL_Label',
        i18nDescription: 'SelfHosted_LLM_URL_Description',
    },
];
